### PR TITLE
captool: fix zstd detection

### PR DESCRIPTION
**Pull request by GeorgeHahn**
### What does this PR do?

Fix zstd-by-extension detection in captool.

### Motivation

Make captool correctly detect capture format by extension name.

### CODE REVIEW

**Comment by GeorgeHahn** [comment]
* **#994** <a href="https://app.graphite.dev/github/pr/DataDog/lading/994?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @GeorgeHahn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by goxberry — APPROVED** [review]
Good catch!

**Comment by GeorgeHahn** [comment]
* **#1002** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1002?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1000** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1000?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#997** <a href="https://app.graphite.dev/github/pr/DataDog/lading/997?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#995** <a href="https://app.graphite.dev/github/pr/DataDog/lading/995?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#994** <a href="https://app.graphite.dev/github/pr/DataDog/lading/994?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @GeorgeHahn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by GeorgeHahn** [comment]
* **#1002** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1002?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1000** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1000?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#997** <a href="https://app.graphite.dev/github/pr/DataDog/lading/997?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#995** <a href="https://app.graphite.dev/github/pr/DataDog/lading/995?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#994** <a href="https://app.graphite.dev/github/pr/DataDog/lading/994?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @GeorgeHahn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Pull request merged**
