### PR TITLE
fix lading.yaml examples

### PR DESCRIPTION
**Pull request by safchain**
### What does this PR do?

Fix lading.yaml examples. `generator` and `blackhole` uses sequence instead of map.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by GeorgeHahn — APPROVED** [review]
Thank you Sylvain!

**Comment by GeorgeHahn** [comment]
@safchain Please sign this commit & force push. Thanks!

**Comment by goxberry** [comment]
For clarity, I believe we require two kinds of signatures: GPG-signed commits (e.g., with `git config commit.gpgsign true`) and commit message sign-offs (e.g., using `git commit -s` when committing changes).

**Comment by GeorgeHahn** [comment]
@safchain Thanks for signing that commit. There's one last thing to do before github will show it as verified: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

**Comment by safchain** [comment]
@GeorgeHahn thanks, I was using the worng gpg key. Now fixed

**Pull request merged**
