### PR TITLE
total_rss_bytes and total_pss_bytes from smaps_rollup

### PR DESCRIPTION
**Pull request by blt**
### What does this PR do?

This commit adds collection of total PSS bytes for all processes from
smaps_rollup, adjusting total_rss_bytes to also be from the same source

### CODE REVIEW

**Comment by blt** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/DataDog/lading/1134?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1134** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1134?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/DataDog/lading/1134?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#1133** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1133?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1130** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1130?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1129** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1129?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1128** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1128?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1127** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1127?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1124** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1124?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1120** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1120?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1125** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1125?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1126** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1126?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by GeorgeHahn — APPROVED** [review]
Change LGTM. Will this change the RSS measurement enough that we'll need to update limits to account for it?

**Comment by blt** [comment]
> Change LGTM. Will this change the RSS measurement enough that we'll need to update limits to account for it?

My expectation is that these measurements will be basically the same, potentially slightly larger. smaps data elides < 1Kb because of the way it rounds, so if a target has a lot of little regions that'll matter. 

Will need to be checked.

**Review by scottopell — APPROVED** [review]

**Comment by scottopell** [comment]
We should deprecate `rss_bytes` (similar to `total_rss_bytes` but per-process) in favor of `smaps_rollup.rss`. OR define `rss_bytes` from `smaps_rollup.rss`

**Comment by blt** [comment]
### Merge activity

* **Dec 6, 3:33 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/lading/1134).

**Pull request merged**
